/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_graal_compiler_test_bytecodefuzz_MutatorHarness */

#ifndef _Included_jdk_graal_compiler_test_bytecodefuzz_MutatorHarness
#define _Included_jdk_graal_compiler_test_bytecodefuzz_MutatorHarness
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_graal_compiler_test_bytecodefuzz_MutatorHarness
 * Method:    initMutator
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jdk_graal_compiler_test_bytecodefuzz_MutatorHarness_initMutator
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
